method-name =  
    "abt" / "btcr" / "stack" / "erc725" / "example" / "ipid" / 
    "life" / "sov" / "uport" / "ethr" / "v1" / "com" / "dom" / 
    "ont" / "vvo" / "aergo" / "icon" / "is" / "iwt" / "ockam" / 
    "ala" / "op" / "jlinc" / "ion" / "jolo" / "bryk" / "peer" / 
    "selfkey" / "meta" / "tys" / "git" / "tangle" / "emtrust" / 
    "ttm" / "wlk" / "pistis" / "holo" / "web" / "io" / "vaultie" / 
    "moac" / "omn" / "work" / "vid" / "ccp" / "jnctn" / "evan" / 
    "elastos" / "kilt" / "elem" / "github" / "bid" / "ptn" / "echo" / 
    "trustbloc" / "san" / "gatc" / "factom" / "signor" / "hedera" / 
    "sirius" / "dock" / "twit" / "near" / "vaa" / "bba" / "morpheus" / 
    "etho" / "bnb" / "celo" / "klay" / "trx" / "grg" / "schema" / "key" /
    "solid"
