did-document = {
    service : [1* serviceEndpoint ]  

}

serviceEndpoint = {
    ; representation-specific properties for JSON-LD
    ? "@content" : ~uri    ; this is an active area of debate if this belongs here
    
    ; representation-independent properties
    id : did-url
    type : text 
    ? description : text 
    serviceEndpoint : ~uri / uri  
}


did-url = text .regexp "did\\:(?<did_method>[a-z0-9]+)\\:(?<did_method_identifier>[A-Za-z0-9\\.\\-\\:\\_]+)\\/?(?<path>[A-Za-z0-9\\/]+)\\??(?<query>[A-Za-z0-9\\=\\&\\%\\-\\:]+)?\\#?(?<fragment>[A-Za-z0-9\\-\\_]+)"







