name: Lint DID Methods
on:
  pull_request:
    paths: ["methods/**"]

jobs:
  lint-did-extensions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code...
        uses: actions/checkout@v7
      - name: Setup Node 24...
        uses: actions/setup-node@v6
        with:
          node-version: 24.x
      - name: Install did-extensions tooling...
        working-directory: tooling
        run: npm i
      - name: Validate did-extensions DID method entries
        working-directory: tooling
        run: npm run validate
      - name: Generate did-extensions registry index
        working-directory: tooling
        run: npm run generate
