name: Github Pages Publication
on:
  push:
    branches:
      - main

jobs:
  publish-did-extensions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code...
        uses: actions/checkout@v4
      - name: Setup Node 22...
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - name: Install did-extensions tooling...
        working-directory: tooling
        run: npm i
      - name: Validate did-extensions DID method entries
        working-directory: tooling
        run: npm run validate
      - name: Generate did-extensions registry index
        working-directory: tooling
        run: npm run generate
      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: .
          token: ${{ secrets.GITHUB_TOKEN }}
          git-config-name: 'didwg[bot]'
          git-config-email: 'didwg[bot]@users.noreply.github.com'
          single-commit: true
